### ISSUE TITLE
"Modernize Folder Picker Dialog" issue when trying to install it on windhawk 1.5.1

### ISSUE THREAD

**Issue by soredake** [ramensoftware/windhawk-mods#833]
```
In file included from c:\ProgramData\Windhawk\EditorWorkspace\mod.wh.cpp:35:
In file included from c:/Program Files/Windhawk/Compiler/include/winrt/base.h:10:
In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/algorithm:1794:
In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__algorithm/copy.h:12:
In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__algorithm/copy_move_common.h:14:
In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__algorithm/unwrap_range.h:19:
In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__utility/pair.h:17:
c:/Program Files/Windhawk/Compiler/include/c++/v1/__fwd/get.h:18:10: fatal error: '__tuple/tuple_element.h' file not found
   18 | #include <__tuple/tuple_element.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

![изображение](https://github.com/user-attachments/assets/e5809f8f-1357-497c-b0ff-050347a73207)

**Comment by m417z** [comment]
Looks like on the files is missing on your computer. Please download Windhawk again, run it and choose "Reinstall". Let me know if it helps.

Also, you're the second user to have this problem, but I'm not sure how it can happen, the file is right there in the archive. If you find any clue regarding how it happened (maybe an antivirus removed it), please let me know, thanks!

There's no steps I can think of for now, so I'm closing this issue.

**Comment by soredake** [comment]
Reinstalling helped, thanks, this file was somehow lost when upgrading 1.4.1 to 1.5.1

**Comment by src52** [comment]
> Reinstalling helped, thanks, this file was somehow lost when upgrading 1.4.1 to 1.5.1

Thanks for posting this, as I experienced the same issue after upgrading to v1.5.1!

**Comment by m417z** [comment]
I just looked again for an explanation for this. [This issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278377), which interestingly about a similar problem on Linux, has an interesting insight:

> On FreeBSD 13.3, /usr/include/c++/v1/__tuple is directory containing several files including "tuple_element.h" [1] whereas on 13.2, /usr/include/c++/v1/__tuple is a single file. [2] I suspect your libcxx installation may have been corrupted when you upgraded from 13.2 to 13.3.

In Windhawk, that means that probably the new compiler version was installed over the old compiler version without removing the old version first. It can happen in two cases:

* Before the update, the Windhawk version was 1.5 or newer according to the registry.
* Before the update, the Windhawk version was missing in the registry.

The first option isn't likely, so it's probably the second option. My best guess is that the information about the Windhawk installation was removed for some reason (maybe a Windows reinstallation), but the files remained in Program Files. I'll look into improving the installer to handle this case.
